import { createActions } from 'redux-actions';

const homeActions = createActions({
  CLEAR_HOME_DATA: undefined,
  GET_BALANCE_REQUEST: undefined,
  GET_BALANCE_SUCCESS: undefined,
  GET_BALANCE_FAILED: undefined,
  SET_TRANSFER_AMOUNT: undefined,
  CREATE_DEPOSIT_REQUEST: undefined,
  CREATE_DEPOSIT_SUCCESS: undefined,
  CREATE_DEPOSIT_FAILED: undefined,
  CREATE_WITHDRAWAL_REQUEST: undefined,
  CREATE_WITHDRAWAL_SUCCESS: undefined,
  CREATE_WITHDRAWAL_FAILED: undefined,
  GET_APEX_BALANCE_REQUEST: undefined,
  GET_APEX_BALANCE_SUCCESS: undefined,
  GET_APEX_BALANCE_FAILED: undefined,
  GET_STOCK_DETAILS_REQUEST: undefined,
  GET_STOCK_DETAILS_SUCCESS: undefined,
  GET_STOCK_DETAILS_FAILED: undefined,
  GET_TIME_SERIES_REQUEST: undefined,
  GET_TIME_SERIES_SUCCESS: undefined,
  GET_TIME_SERIES_FAILED: undefined,
  SET_STOCK: undefined,
  GET_TRANSACTIONS_REQUEST: undefined,
  GET_TRANSACTIONS_SUCCESS: undefined,
  GET_TRANSACTIONS_FAILED: undefined,
  GET_TRANSACTION_DETAIL_REQUEST: undefined,
  GET_TRANSACTION_DETAIL_SUCCESS: undefined,
  GET_TRANSACTION_DETAIL_FAILED: undefined,
  TRANSACTION_CANCEL_REQUEST: undefined,
  TRANSACTION_CANCEL_SUCCESS: undefined,
  TRANSACTION_CANCEL_FAILED: undefined,
  GET_STORIES_REQUEST: undefined,
  GET_STORIES_SUCCESS: undefined,
  GET_STORIES_FAILED: undefined,
  SET_CLOSE_REASON_REQUEST: undefined,
  SET_CLOSE_REASON_SUCCESS: undefined,
  SET_CLOSE_REASON_FAILED: undefined,
});

export { homeActions };
